### ISSUE TITLE
maven 循环依赖问题

### ISSUE THREAD

**Issue by walkertest** [TarsCloud/TarsJava#100]
* tars-core依赖 tars-net;
* 如果tars-net需要依赖tars-core中HexUtil工具类，会引起循环依赖报错.

----
建议再抽出一个单纯的依赖包，解决这个循环依赖的问题.
或者其它思路.

**Comment by TimmyYu** [comment]
若是有循环依赖。可以使用exclude 排掉同样版本的依赖
