### ISSUE TITLE
Cannot resolve com.tencent.tars:tars-spring-boot-starter:1.7.0-SNAPSHOT

### ISSUE THREAD

**Issue by yngyuan** [TarsCloud/TarsJava#103]
按照 https://tarscloud.github.io/TarsDocs/dev/tarsjava/tars-http-server.html 的 tars-spring-boot-http-server开发教程添加pom依赖时IDEA报错

**Comment by yukkiball** [comment]
现在已经不是SNAPSHOT版本，可以使用最新的1.7.2版本，所有的版本可以参考https://mvnrepository.com/artifact/com.tencent.tars/tars-spring-boot-starter

**Comment by yngyuan** [comment]
使用1.7.1 解决了
