### ISSUE TITLE
it will throw exception when starting a server without stat and property

### ISSUE THREAD

**Issue by keranbingaa** [TarsCloud/TarsJava#108]
when I don't config stat and property, it will throw some exception when I  start server.

I think stat and property is optional server, but even if I don't config the stat and property in config file, it will also throw the exception. I can avoid this by change the  source code, is there any other way to avoid it?

**Comment by wqliang** [comment]
Would it be better not start the scheduled task of property if the propertyObj is null ? Or using a propertyEnable flag to determine wether or not start the property task ?

**Comment by TimmyYu** [comment]
The service should not have started when the framework property server is  down
