### ISSUE TITLE
日志框架强绑定到logback 问题

### ISSUE THREAD

**Issue by Qi382** [TarsCloud/TarsJava#114]
建议项目中使用slf4j 框架，不应该强制用户使用logback @TimmyYu

**Comment by TimmyYu** [comment]
logback现在已经覆盖了所有的日志的覆盖的需求，整体的实现是高效的，设计是灵活的。在支持的一部分用户中使用logback的确实是没有问题。但是也使用其他日志控制器的同学，后续还是会以logback作为框架的默认实现， 但是一部分升级到新框架版本的用户，确实无法快速的统一掉框架实现，确实这一部分应该有选择的权利

**Comment by TimmyYu** [comment]
会在新的2.0的版本和1.7.4的版本中。处理这一个问题

**Comment by wqliang** [comment]
> 会在新的2.0的版本和1.7.4的版本中。处理这一个问题

请问1.7.4版本计划什么时候release？
