### ISSUE TITLE
[bug]客户端拉取到到服务列表顺序不同时会误触发refresh

### ISSUE THREAD

**Issue by diracccc** [TarsCloud/TarsJava#115]
## 现象
服务端没有节点扩缩容的情况下，客户端`ObjectProxy`拉取服务端列表后执行了`refresh`刷新列表。
线上服务真实出现。

## 原因
服务端一共A B C三个节点。
第一次拉取得到：A B C，`QueryHelper#getServerNodes`返回的nodes字符串顺序为ABC顺序；
第二次拉取得到：A C B，`QueryHelper#getServerNodes`返回的nodes字符串顺序为ACB顺序。
然后直接对比字符串判定发生改变，触发`refresh`
```java
if (nodes != null && !nodes.equals(servantProxyConfig.getObjectName())) {
    servantCacheManager.save(communicator.getId(), servantProxyConfig.getSimpleObjectName(), nodes, communicator.getCommunicatorConfig().getDataPath());
    servantProxyConfig.setObjectName(nodes);
    refresh();
}
```

**Comment by TimmyYu** [comment]
这一部分是由于在拉取的时候 ，没有处理排序导致的。新版本中（1.6.2或者 1.7.1版本之后解决了这个问题 ）， 字符串的对比会比节点的iterator会更高效一些
https://github.com/TarsCloud/TarsJava/commit/2df3f2f62762cdafba8a7a2f3860637da1fe27d6
