### ISSUE TITLE
你好，请问下tarsjava1.6.1版本遇到了余下问题，不知道新版本有没有解决

### ISSUE THREAD

**Issue by chenhuandong8010** [TarsCloud/TarsJava#129]
tarsjava1.6.1版本以前遇到的问题:
1、高并发查询时，session不断的创建和destroy;
2、回包大小限制，最大10M；
3、tarsjava进程挂掉后无法自动拉起，手动拉起偶尔都会失败;
4、tarsjava底层gc频繁；
5、tarsjava或者tarsjava springboot/spring提供http服务时，负载不太均衡；

**Comment by TimmyYu** [comment]
tarsjava1.6.1版本以前遇到的问题:
1、高并发查询时，session不断的创建和destroy; -> 这个并不会哈。需要看一下客户端是不是超过了超时的时间或者一部分的请求使用的是短链接请求服务 
2、回包大小限制，最大10M； -> 这个会在后续的版本中包的大小可配置
3、tarsjava进程挂掉后无法自动拉起，手动拉起偶尔都会失败; ->可以看一下具体的服务的错误的日志，若是在启动的时候 ，是在启动项内过多，那么是超过了tarsnode启动的1秒时间 ，可以更新tarsnode解决
4、tarsjava底层gc频繁； ->建议可以看一一日志gc是由于什么对象引起的。调整 cms参数或者查看创新大量对象的结构体是什么
5、tarsjava或者tarsjava springboot/spring提供http服务时，负载不太均衡； -》这一部分负载是依赖于nginx的负载，可以查看nginx的配置
