### ISSUE TITLE
请问下如何可以做到二进制包透传的功能？

### ISSUE THREAD

**Issue by kakayu** [TarsCloud/TarsJava#143]
想实现一个代理层服务，代理层收到二进制包后，可以做一些通用的过滤，比如合并查询，鉴权等，然后将收到的包原封不动的转发给后端的服务，但不希望后端的服务每增加一个接口，代理层服务都要更新发版。

**Comment by TimmyYu** [comment]
这个可以关注一下apigateway后续是否会开放这个功能
