### ISSUE TITLE
[bug]Selector空轮询CPU冲高问题

### ISSUE THREAD

**Issue by diracccc** [TarsCloud/TarsJava#15]
在使用中出现过Selector空转的bug，希望能有netty、grizzly这样的重建Selector的规避方案。

**Comment by TimmyYu** [comment]
这个只在jdk1.6.02和固定的LINUX 版本中会有。在JDK1.8配合 cenots 6及以上的版本是不会有这个问题的。具体的定位点。可以在你CPU冲高的时候 。使用JSTACK查看即可。
