### ISSUE TITLE
“TarsAbstractCallback” Has been removed, example: tars-spring-boot-http-server cannot be compiled ！

### ISSUE THREAD

**Issue by wincsb** [TarsCloud/TarsJava#160]
[ERROR] /E:/Gitee/Tars/TarsJava/examples/tars-spring-boot-http-server/src/main/java/com/tencent/tars/client/testapp/HelloPrxCallback.java:[10,48] 找不到符号
  符号: 类 TarsAbstractCallback

![Uploading 图片.png…]()

**Comment by TimmyYu** [comment]
Callback在Master的版本中不再被使用。被CompleableFuture代替。所以测试的时候 。使用1.7的版本即可。新的功能也不会合并进正常的版本中。
