### ISSUE TITLE
如何在一台机器上部署多个tars springboot 实例

### ISSUE THREAD

**Issue by belonace** [TarsCloud/TarsJava#21]
如何在一台机器上部署多个tars springboot 实例？springboot在启动的时候必须指定http端口，如果要在一台机器部署同样的服务的多个springboot实例，应该怎么配置呢？目的是为了高效的利用机器资源。

**Comment by TimmyYu** [comment]
在配置平台里面，SERVNAAT的端口配置使用不同的端口即可

**Comment by TimmyYu** [comment]
可以使用docker部署，可实现一台物理机上多个tars实例
