### ISSUE TITLE
1.7.4 was not found in maven

### ISSUE THREAD

**Issue by lizongying** [TarsCloud/TarsJava#214]
cd TarsJava/examples/tars-spring-boot-server && mvn package

[ERROR] Failed to execute goal on project tars-spring-boot-server: Could not resolve dependencies for project com.tencent.tars:tars-spring-boot-server:jar:1.7.4: The following artifacts could not be resolved: com.tencent.tars:tars-spring-boot-starter:jar:1.7.4 (absent): com.tencent.tars:tars-spring-boot-starter:jar:1.7.4 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by KahnCheny** [comment]
1.7.4 It has been deployed. Wait for the central repository to synchronize.

**Comment by lizongying** [comment]
@KahnCheny 感謝
