### ISSUE TITLE
[讨论]  为什么TarsJava里面要自己实现Logger，不用已有的框架呢

### ISSUE THREAD

**Issue by woodwind** [TarsCloud/TarsJava#25]
如果使用自己实现的Logger，在程序里面很难控制这块的处理，而且目前看下来，可能是因为要做remote logging所以自己做了实现？
这块应该可以有更好的处理方案吧，比如使用常用的日志框架和实现，并增加自定义appender？

**Comment by TimmyYu** [comment]
使用LOGBACK替换原本的日志控制器已经在进行了。

**Comment by knfcn** [comment]
Logger已经在优化中
