### ISSUE TITLE
[Bug]自带logger存在内存泄漏

### ISSUE THREAD

**Issue by Deniulor** [TarsCloud/TarsJava#26]
![image](https://user-images.githubusercontent.com/5369212/60379081-f7697e00-9a5e-11e9-958b-fb14536889a6.png)

如图Writer的Close，并没有把这个FileOutputStream的资源释放掉
附：
jmap  dump 下来的dump文件显示，大量的finalizer都在等待这个fos释放：
![image](https://user-images.githubusercontent.com/5369212/60379104-48797200-9a5f-11e9-9e93-2fcce64eb922.png)
ps: 这个服务器只是跑了一天，使用频率一小时可能才有一两次的访问

**Comment by walkertest** [comment]
retained heap是2M吗？ 这样的话，占比也不多吧

并且FileOutputStream 占比是 0.01%吧？
看上去代码 finally中，是有close的吧？

**Comment by Deniulor** [comment]
> retained heap是2M吗？ 这样的话，占比也不多吧
> 
> 并且FileOutputStream 占比是 0.01%吧？
> 看上去代码 finally中，是有close的吧？

![image](https://user-images.githubusercontent.com/5369212/60409006-15b4b280-9bf4-11e9-83cc-b17f6d548336.png)
可以看到这边应该是已经close掉了

但是目前看，这种写一次logger，就进行一次fos的创建，会导致后期的GC难度变大。
看了笨神的文章：http://lovestblog.cn/blog/2015/07/09/final-reference/
这边介绍是fos会在内存中不断堆积，从而产生后续的gc问题。
从dump中看，一次占用0.01%的量还是很恐怖的

**Comment by TimmyYu** [comment]
下面的这一个版本日志控制器会换成LOGBACK。。不会使用这个老的日志控制器处理了。所以

**Comment by TimmyYu** [comment]
新版本已经替换掉原本的日志控制器
