### ISSUE TITLE
ServantProxyFactory性能问题

### ISSUE THREAD

**Issue by vicklin** [TarsCloud/TarsJava#28]
ServantProxyFactory用了concurrentHashMap，为什么还要加个lock？

**Comment by TimmyYu** [comment]
这里是需要加上锁的。不然存在ObjectProxy会生成两次。虽然不会进入map中替换掉。这种情况 下。还要把这个重复生成的代理类再销毁 。
这里加锁并不影响实际的生产的性能 ，仅在系统开启的时候 。处理。在SPRING中也常见
