### ISSUE TITLE
tars.springboot模板数据有问题

### ISSUE THREAD

**Issue by zengjunyu** [TarsCloud/TarsJava#3]
![image](https://user-images.githubusercontent.com/8214239/47343343-75a7a080-d6d8-11e8-8211-902f0167b34a.png)
tars.springboot的模板多了一个 '<' ，这样会导致发布spring服务的时候，没有办法正确的解析模板，导致服务发布失败

解决方案：
修改TarsFramwork->sql->db_tars.sql文件中插入t_profile_template表中的默认数据

**Comment by TimmyYu** [comment]
新版本的平台上面已经没有这样的问题，可以更新到新的版本的平台使用Docker编译部署即可
