### ISSUE TITLE
com.qq.tars.server.core.AppContextListener 在springboot中怎么使用呢

### ISSUE THREAD

**Issue by 279259621** [TarsCloud/TarsJava#33]

**Comment by TimmyYu** [comment]
public class AppStartListener implements ApplicationListener<ApplicationEnvironmentPreparedEvent> 


直接使用spirngboot内置的listener就好了。不需要这样操作了。

**Comment by TimmyYu** [comment]
![image](https://user-images.githubusercontent.com/1688061/64902791-6494c300-d6e0-11e9-868b-5261e2ba3e2f.png)
比如这样
