### ISSUE TITLE
所以这个项目只merge自己的pr吗？

### ISSUE THREAD

**Issue by zehuaiWANG** [TarsCloud/TarsJava#42]
issue和pr都多久没review了，今天收到一个接受的pr竟然是作者自己提的。

**Comment by KatharineOzil** [comment]
好像之前是contributor升级为owner

**Comment by TimmyYu** [comment]
刚刚看到您这里提交的request了，因为处理点较多，所以统一在新特性的promise版本中统一处理了，感谢这位同学的提交 ，希望多给tars项目提提供新的功能和意见 ，我们也乐意合好的request.

**Comment by zehuaiWANG** [comment]
@TimmyYu 其实我觉得你们可以多任命几个有能力的管理员来做代码的review，这才是开源的目的，这样社区才会活跃，也不至于很久没人看到pr，明明现在的pr量很少。
