### ISSUE TITLE
[Bug] ConfigHelper not work properly when using tars-spring-boot-starter

### ISSUE THREAD

**Issue by woodwind** [TarsCloud/TarsJava#43]
Our team uses tars as our rpc framework and we are trying to adopt the sprint-boot version of tars.
In general, we use tars console and ConfigHelper to manage our config files. In tars spring boot, the server template use java -jar rather than -cp to run the spring boot application, such that the class path configuration is ignored. 
ConfigHelper will load files into {basepath}/conf, so this path should be added to resources location in tars-spring-boot-starter.

**Comment by TimmyYu** [comment]
use  maven plugin 
   <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <Class-Path>conf/</Class-Path>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>

**Comment by woodwind** [comment]
@TimmyYu using maven plugin works and I found another solution which leverage service template.

1. add loader.path in jvmparams
2. change layout to ZIP in spring-boot-maven-plugin
```
          <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <layout>ZIP</layout>
                    <mainClass>...</mainClass>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Should be better for multiple services ops.
