### ISSUE TITLE
stringToProxy传ServantProxyConfig无法设置setDivision为null

### ISSUE THREAD

**Issue by wqliang** [TarsCloud/TarsJava#56]
由同一个Communicator获取不同servant的proxy，调用servant的超时时间都是相同的。现在，想实现每个servant能够有各自的超时时间，为了减少创建的Communicator数量，使用同一个Communicator获取proxy，通过`stringToProxy(Class<T> clazz, ServantProxyConfig servantProxyConfig)`中的ServantProxyConfig来为每个servant设置不同的超时参数。

ServantProxyConfig默认的SetDivision值为“”（空字符串），并且setSetDivision方法无法将值设置为null。在`ObjectProxyFactory.getObjectProxy`中，通过判断SetDivision是否为null来确定如何设置赋值，这就导致了通过上述stringToProxy接口来获取proxy时，SetDivision一定得设置。

有几个问题：
1、是否可以提个PR将ServantProxyConfig的SetDivision默认值改为null，或者将ObjectProxyFactory.getObjectProxy中对SetDivision的判断改为isEmpty判断，或者修改setSetDivision使其允许将值设置null；
2、除了创建多个Communicator，是否有其他推荐的做法来到达不同servant设置不同超时的效果；

**Comment by TimmyYu** [comment]
谢谢返回这个问题已经在新版本的提交中解决了。  感谢提交
