### ISSUE TITLE
是否有gradle的tars2java插件？

### ISSUE THREAD

**Issue by wqliang** [TarsCloud/TarsJava#59]
tars官方给的指引，是用maven来管理项目的，如果使用gradle，是否有对应的tars2java插件？或者有什么方式能够在gradle项目中使用tars2java？

**Comment by qianjin** [comment]
用maven把tars2Java的插件生成，生成后就可以一直用，跟项目用gradle和maven没有关系的，tars2java插件主要还是将tars协议转成java文件用

**Comment by wqliang** [comment]
> 用maven把tars2Java的插件生成，生成后就可以一直用，跟项目用gradle和maven没有关系的，tars2java插件主要还是将tars协议转成java文件用

@qianjin 没错，我现在也是这样做。但每次开发新的或者修改接口，都需要在maven里生成这个java文件，然后再更新到gradle管理的项目里去，比较麻烦。

**Comment by TimmyYu** [comment]
现在仅支持maven， 还不支持gradle，若是有gradle的插件 可以提交
