### ISSUE TITLE
tars协议生成的客户端代理类是不是还不支持Future版本

### ISSUE THREAD

**Issue by laidahe** [TarsCloud/TarsJava#6]
![image](https://user-images.githubusercontent.com/13506234/48975885-3644e900-f0b6-11e8-9460-1398a8be0e9d.png)
tars协议生成的客户端代理类是不是还不支持Future版本,我记得c++都有支持 Future 版本的。
Future版本要比回调类的模式好用。

**Comment by TimmyYu** [comment]
PROMISE的版本已经提交了。REQEUST已经提了。。后面审核后是可以使用的

**Comment by TimmyYu** [comment]
新的版本已经审核过了。可以编译新的生成plugin后。就可以生成promise 的版本了

**Comment by TimmyYu** [comment]
新的masgter版本已经支持COmpletabletFUTURE的promise版本了。可以使用
