### ISSUE TITLE
tup version=2协议编解码问题

### ISSUE THREAD

**Issue by walkertest** [TarsCloud/TarsJava#61]
# 线上问题描述
* 实际完整调用链路：  client(ios&android) --> tupProxy(C++实现)  ---> taf java server
* C++侧的tup proxy通过tup version=2的协议，将请求转发到tars java服务；
* 但是服务的接口侧收到的请求参数为null.

**Comment by TimmyYu** [comment]
请求的场景：
在Client(Ios Or Android ) -> TupProxyServer -> javaServer这样的请求链中。TUpProxyServer使用tup协议进行通信 。默认使用的TarsVersion是2，这种解析情况下解析判断依赖于_newData ==null的值 。会有异常com.qq.tars.protocol.tars.exc.TarsDecodeException: type mismatch

解决：
当tupVersion ==2，encode和decoder解析之前，将_newData字段符值==null，可以解决tupVersion==2 时解析的问题
