### ISSUE TITLE
一次请求的串联，有类似traceid的东西吗，协议里

### ISSUE THREAD

**Issue by TARS-Robot-Question** [TarsCloud/TarsJava#68]
我想在日志里，将请求串联起来，应该怎么弄

还是说要结合 ：https://github.com/TarsCloud/TarsJava/blob/master/docs/tars_tracing.md 这个才可以使用。我要怎么get到 traceid，打印在日志里？

**Comment by TARS-Robot-Answer** [comment]
这个是链路追踪 ，你要一整条请链追踪的时候 。可以使用。若是仅要追一个人的数据的话。1.7可以使用logback自带的功能做数据追踪，1.6的话。在日志控制器里面配上你要追踪的字段和数据 。是可以单独打印出你需要的日志。

**Comment by TARS-Robot-Question** [comment]
这个链路追踪的 traceid的服务之间的传递，是放在tars协议里的哪一块

**Comment by TARS-Robot-Answer** [comment]
Context 

![WechatIMG6140c13db2461a992fcbc03c80e3e4cf](https://user-images.githubusercontent.com/62691722/77628903-a94cc100-6f83-11ea-8f14-cbd22441aaf9.jpeg)
