### ISSUE TITLE
tars java可以支持json协议吗?

### ISSUE THREAD

**Issue by TARS-Robot-Question** [TarsCloud/TarsJava#69]
改造一个老项目，很多依赖应用用的http协议，好像tars c++是支持的

**Comment by TARS-Robot-Answer** [comment]
使用springboot的功能就可以支持所有的http的功能了，具体的返回json的功能按自己协议定就好了。

http的协议上面的功能 ，java里面已经有很完善的体系springBoot了。http的处理不管是异步还是同步都有很高的实践的结果 ，所以java部分的http的方向也是走现在有的组件来提供http的服务。
