### ISSUE TITLE
hello-world无法发布

### ISSUE THREAD

**Issue by KimRasak** [TarsCloud/TarsJava#75]
跟随[tarsJava快速入门](https://tarscloud.github.io/TarsDocs/hello-world/tarsjava.html)，执行`mvn package`后，准备将war包发布到web管理平台上。
跟随[tarsJava发布](https://www.bookstack.cn/read/Tars-1.8/rumen-hello-world-1-README.md)执行后，服务无法开启，始终处于inactive状态:

![](https://upload-images.jianshu.io/upload_images/7547741-104cc1650766ae51.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![](https://upload-images.jianshu.io/upload_images/7547741-64b6337555ec47c9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

请问是什么原因？谢谢！

**Comment by TimmyYu** [comment]
无法驱动有很多的问题，具体需要上传一下你的日志看一下

**Comment by ruanshudong** [comment]
一直这样? 框架重启一下呢?
/usr/local/app/tars/tars-start.sh

**Comment by KimRasak** [comment]
问题已解决，是因为我自己的问题，上线的服务容器名与编码的服务端不同，导致服务无法启动。但当时不知道如何查看报错，耗费了一些时间。
请问怎么查看日志呢？

**Comment by TimmyYu** [comment]
> 问题已解决，是因为我自己的问题，上线的服务容器名与编码的服务端不同，导致服务无法启动。但当时不知道如何查看报错，耗费了一些时间。
> 请问怎么查看日志呢？

 在平台上面点击服务后。就可以查看得到日志
