### ISSUE TITLE
CommunicatorConfig中的参数refreshEndpointInterval不起作用

### ISSUE THREAD

**Issue by keepthinker** [TarsCloud/TarsJava#77]
查看1.5.0 TarsJava源码，发现CommunicatorConfig中refreshEndpointInterval不起作用，没有任何代码引用此参数，按官方文档的意思是，refreshEndpointInterval是“定时去registry刷新配置的时间间隔”。是不是此处有问题，按代码里的逻辑，应该最终将refreshEndpointInterval参数设置到ServantProxyConfig的refreshInterval参数里，但是没看到设置。
说实话刷新默认时间设置成1分钟，也太长了，难道服务还得等1分钟才能调用，不让就超时或失败，希望今后加入准实时感应服务节点变更情况，比如像zookeeper主动通知服务变更机制。

**Comment by TimmyYu** [comment]
bug已经在新版本中修复 。感谢提交
