### ISSUE TITLE
TarsJava tars-spring-cloud-client 启动报错

### ISSUE THREAD

**Issue by longfei9527** [TarsCloud/TarsJava#9]
application.yml配置如下：
eureka:
  client:
    serviceUrl:
      #服务注册中心的地址
      defaultZone: http://localhost:8761/eureka/
      #客户端不需要向spring cloud主控注册
      register-with-eureka: false

报错:
Description:

Disconnected from the target VM, address: '127.0.0.1:56002', transport: 'socket'
Field clientProperties in com.qq.tars.register.eureka.EurekaRegisterHandler required a bean of type 'com.qq.tars.spring.config.TarsClientProperties' that could not be found.

Action:

Consider defining a bean of type 'com.qq.tars.spring.config.TarsClientProperties' in your configuration.

**Comment by TimmyYu** [comment]
包没有找到。看看具体的引入的tars项目包是否正确。版本是否统一
